site_name: simple-homepage
repo_url: https://github.com/fpgmaas/simple-homepage
site_url: https://fpgmaas.github.io/simple-homepage
site_description: Create a simple homepage
site_author: Florian Maas

nav:
  - Home: index.md
  - Getting Started: getting_started.md
  - Commands: commands.md
  - Demo: 
    - Light: demo/light/homepage.html
    - Dark: demo/dark/homepage.html
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
            setup_commands:
                - import sys
                - sys.path.append('../')
copyright: Maintained by Florian Maas.
theme:
  name: material
  feature:
    tabs: true
  palette:
    primary: white
    accent: blue
markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true